# Generated by Django 5.2.4 on 2026-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='categoria_en',
            field=models.CharField(blank=True, max_length=3000, verbose_name='Category (EN)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (EN)'),
        ),
    ]
