# Generated by Django 5.2.4 on 2026-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herophotos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herophoto',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Subtitle (EN)'),
        ),
        migrations.AddField(
            model_name='herophoto',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (EN)'),
        ),
    ]
