# Generated by Django 5.2.4 on 2026-06-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Ej. 100 × 80 cm', max_length=100, verbose_name='Dimensiones'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (€)'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='technique',
            field=models.CharField(blank=True, help_text='Ej. Óleo sobre lienzo', max_length=150, verbose_name='Técnica'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='year',
            field=models.CharField(blank=True, max_length=10, verbose_name='Año'),
        ),
    ]
