# Generated by Django 5.2.4 on 2026-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_galleryimage_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='dimensions_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dimensions (EN)'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='paper_size_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Paper size (EN)'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='technique_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Technique (EN)'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, verbose_name='Title (EN)'),
        ),
    ]
