# Generated by Django 5.2.4 on 2026-06-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_blogs', models.CharField(default='Eportfolios', max_length=50, verbose_name='Menú · Blogs')),
                ('nav_events', models.CharField(default='Tips', max_length=50, verbose_name='Menú · Events')),
                ('nav_gallery', models.CharField(default='Galería', max_length=50, verbose_name='Menú · Galería')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
