# Generated by Django 5.2.4 on 2026-06-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='Sigfrid', max_length=80, verbose_name='Título del sitio'),
        ),
    ]
