# Generated by Django 5.2.4 on 2026-06-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_sitesettings_site_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo / favicon'),
        ),
    ]
