# Generated by Django 5.2.4 on 2026-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#c2a878', max_length=7, verbose_name='Color de acento'),
        ),
    ]
