# Generated by Django 5.2.4 on 2026-06-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_sitesettings_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bio/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Texto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de la biografía',
                'verbose_name_plural': 'Fotos de la biografía',
                'ordering': ['order', '-created_date'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bio_photo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Foto de la biografía'),
        ),
    ]
