# Generated by Django 5.2.4 on 2026-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_rename_nav_events_to_nav_miscellany'),
    ]

    operations = [
        migrations.AddField(
            model_name='biophoto',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Caption (EN)'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location (EN)'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bio_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Biography (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Text under the hero (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_blogs_en',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Menu · Blogs (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_gallery_en',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Menu · Gallery (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_miscellany_en',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Menu · Miscellany (EN)'),
        ),
    ]
