# Generated by Django 5.2.4 on 2026-06-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_biophoto_caption_en_exhibition_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_signature',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Firma del footer'),
        ),
    ]
