# Generated by Django 5.2.4 on 2026-06-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_sitesettings_footer_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='products_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Imagen del hero de productos'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_hero_text',
            field=models.TextField(blank=True, default='', verbose_name='Texto del hero de productos'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_hero_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Products hero text (EN)'),
        ),
    ]
