# Generated by Django 5.2.4 on 2026-06-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_sitesettings_products_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='products_hero2_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Imagen del segundo hero de productos'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_hero2_text',
            field=models.TextField(blank=True, default='', verbose_name='Texto del segundo hero de productos'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_hero2_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Products second hero text (EN)'),
        ),
    ]
