# Generated by Django 5.2.4 on 2026-06-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_sitesettings_products_hero2_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='exhibitions_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Imagen del hero de exhibiciones'),
        ),
    ]
