# Generated by Django 5.2.4 on 2026-06-20 16:11

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscellanyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Miscellany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('video', models.FileField(blank=True, help_text='Archivo de vídeo (.mp4). Si lo subes, se muestra en lugar de la imagen.', null=True, upload_to='event_videos/', verbose_name='Vídeo')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_miscellany', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_miscellany', to='miscellany.miscellanycategory')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
