# Generated by Django 5.2.4 on 2026-06-20 18:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellany',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='miscellany',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='miscellanycategory',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title (EN)'),
        ),
    ]
