# Generated by Django 5.2.4 on 2026-06-20 19:49

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title_en', models.CharField(blank=True, max_length=250, verbose_name='Title (EN)')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('size', models.CharField(blank=True, max_length=150, verbose_name='Tamaño')),
                ('technique', models.CharField(blank=True, max_length=150, verbose_name='Técnica')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, verbose_name='Description (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
